;;; revu-reviewed.el --- Mark what has been read as Reviewed  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Jonas Rodrigues

;; Author: Jonas Rodrigues

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; A Reviewed mark is the reviewer's assertion that they have read a
;; region, and the digest of what they read is the mark's identity
;; (ADR-0009).  Whether the assertion still holds is derived, never
;; stored: a hunk is reviewed exactly while its current content hashes to
;; some mark, so an edit un-reviews it with no staleness flag to keep in
;; step, and reverting the edit brings the mark back.  Marks that match
;; nothing are kept for exactly that reason.
;;
;; A diff persists hunk marks only.  Marking a file reviewed takes one
;; mark per hunk, and the file reads as reviewed while every hunk of it
;; matches -- a file-level mark could go on claiming the file was read
;; after a hunk under it changed, which is the lie this design exists to
;; prevent.
;;
;; The digest covers the hunk's body lines with the origin character each
;; diff line carries, and nothing else: the `@@' header and the line
;; numbers around it regenerate on every `git diff' and are no part of
;; what the reviewer read.
;;
;; Where a region stands against the marks is its Reviewed state, derived
;; on every render and never persisted: `reviewed' while its content
;; matches a mark, `stale' while a mark was taken over it and no longer
;; matches it, and unreviewed while none was ever taken.  Telling stale
;; from unreviewed is what the mark's span is for -- a digest that matches
;; nothing says something under this path was read and changed, and the
;; span says which region it was, so a hunk an agent rewrote under the
;; reviewer is not confused with one nobody has read.
;;
;; Marking collapses what it marks, badges its heading with the state,
;; and moves the reviewer on to the heading of the next sibling in Source
;; order that is rendered, reviewed or not: hunk to hunk within a file,
;; and off the last hunk of one file to the file below it.  A heading
;; under a fold is not one point can be left on -- Emacs pushes point out
;; of invisible text and past everything the fold covers -- so a heading
;; folded over is stood for by the heading of the fold, and no fold is
;; opened to make room.  A run advances from the last section it covered,
;; and unmarking moves point nowhere at all.
;;
;; A region across sibling headings marks the whole run it selects, in one
;; Sidecar write and one render; the selection is a gesture and is
;; persisted nowhere, because the marks it leaves are the marks one press
;; per section would have left (ADR-0008).  Collapse is never the only
;; sign that a mark was taken: it is ambiguous against a fold the reviewer
;; made by hand, it goes when the section is opened again, and it is not
;; there at all with hide-reviewed off.  Two buffer-local filters --
;; annotated-only and hide-reviewed -- shape the render and compose:
;; reviewed and annotated are orthogonal, so a hunk with an open question
;; can be marked reviewed and still be found by the annotated-only
;; filter.
;;
;; Reviewed marks are reviewer-private: the Export drops them and the
;; agent contract says nothing about them.

;;; Code:

(require 'cl-lib)
(require 'magit-section)
(require 'seq)
(require 'revu-diff)
(require 'revu-record)
(require 'revu-render)
(require 'revu-sidecar)

;; The review buffer's state and its render live in `revu.el', which
;; requires this file; naming them here would be a loading cycle.
(defvar revu--sidecar)
(defvar revu--files)
(declare-function revu-render "revu")
(declare-function revu-review "revu")

(defvar-local revu-reviewed-hide-reviewed nil
  "Non-nil while this review buffer leaves reviewed sections out.")

(defvar-local revu-reviewed-annotated-only nil
  "Non-nil while this review buffer renders only what carries Annotations.")

;;;; What a mark is taken over

(defun revu-reviewed-hunk-digest (hunk)
  "Return the digest identifying the content of HUNK.
Only the hunk's body lines take part, each with the origin character the
diff wrote it with.  The `@@' header is left out: its boundaries and
numbers are regenerated by every diff and say nothing about whether the
reviewer has read these lines (ADR-0009)."
  (revu-digest (mapconcat (lambda (line) (nth 2 line))
                          (revu-diff-hunk-lines hunk)
                          "\n")))

(defun revu-reviewed--file (files path)
  "Return the file of FILES rendered at PATH, or nil when there is none."
  (seq-find (lambda (file) (equal (revu-diff-file-path file) path)) files))

(defun revu-reviewed--hunks (files value)
  "Return the hunks of FILES the section valued VALUE covers, in render order.
VALUE is a file section's value -- the path -- or a hunk section's, which
is the path and the `@@' header the hunk was rendered with."
  (if (consp value)
      (let ((file (revu-reviewed--file files (car value))))
        (seq-filter (lambda (hunk) (equal (revu-diff-hunk-header hunk) (cdr value)))
                    (and file (revu-diff-file-hunks file))))
    (let ((file (revu-reviewed--file files value)))
      (and file (revu-diff-file-hunks file)))))

(defun revu-reviewed--path (value)
  "Return the path the section valued VALUE belongs to."
  (if (consp value) (car value) value))

(defun revu-reviewed-hunk-span (hunk)
  "Return the base-file lines HUNK covers, as (START . END), END exclusive.
The base side is the one that holds still: a diff is taken against a
pinned Revision, so editing the worktree moves a hunk on the new side
while leaving the old lines it grew out of where they were.  That is what
makes the span usable for saying which mark a changed hunk came from.

A hunk that only adds lines covers no base line at all.  Its span is the
one line it was inserted at, so a mark taken over that line can still be
attributed to it rather than to nothing."
  (let ((start (revu-diff-hunk-old-start hunk))
        (covered (seq-count (lambda (line) (not (equal (nth 0 line) "added")))
                            (revu-diff-hunk-lines hunk))))
    (cons start (+ start (max covered 1)))))

(defun revu-reviewed--spans-overlap-p (one other)
  "Return non-nil when the spans ONE and OTHER cover a base line in common."
  (and one other
       (< (car one) (cdr other))
       (< (car other) (cdr one))))

(defun revu-reviewed--assertions (files value)
  "Return what the section of FILES valued VALUE is read by, as (DIGEST . SPAN).
A diff is read hunk by hunk, so a section covering several of them is
asserted one digest at a time, each with the base lines that hunk covers.
A plain file has no hunks to divide it, so the assertion degrades to a
single digest over the whole content the reviewer read, verbatim, and to
no span: the path is all the locality it has (ADR-0009, ADR-0011)."
  (let ((file (revu-reviewed--file files (revu-reviewed--path value))))
    (if (and file (revu-diff-file-plain file))
        ;; A file that is gone has no content to have been read.
        (when (revu-diff-file-content file)
          (list (cons (revu-digest (revu-diff-file-content file)) nil)))
      (mapcar (lambda (hunk)
                (cons (revu-reviewed-hunk-digest hunk)
                      (revu-reviewed-hunk-span hunk)))
              (revu-reviewed--hunks files value)))))

(defun revu-reviewed--digests (files value)
  "Return the digests the section of FILES valued VALUE is read by."
  (mapcar #'car (revu-reviewed--assertions files value)))

;;;; Whether a mark still holds

(defun revu-reviewed--marked-p (review digest)
  "Return non-nil when some mark of REVIEW asserts DIGEST was read."
  (seq-find (lambda (mark) (equal (revu-mark-digest mark) digest))
            (revu-review-marks review)))

(defun revu-reviewed-p (review files value)
  "Return non-nil when REVIEW records the section of FILES valued VALUE as read.
A hunk is reviewed while its content matches a mark; a file while every
hunk of it does.  A file showing no hunks at all -- a rename that changed
nothing -- is not reviewed by vacuity: there is nothing a mark could have
been taken over."
  (let ((digests (revu-reviewed--digests files value)))
    (and digests
         (not (seq-find (lambda (digest)
                          (not (revu-reviewed--marked-p review digest)))
                        digests)))))

;;;; Which of the three states a region is in

(defvar revu-reviewed--dangling-memo nil
  "Where the render under way memoises its dangling marks, by path.
Every hunk of a file asks the same question of the same marks, so
answering it once a file rather than once a hunk is what keeps a render
of a large Source from costing the square of what it shows.  The table
belongs to one render and is thrown away with it, so nothing it holds can
outlive the state it was derived from.")

(defun revu-reviewed--dangling-marks (review files path)
  "Return every mark of REVIEW on PATH that no region FILES renders matches.
These are the assertions the reviewer made that no longer hold: what was
read under PATH is not there any more.  Which region each one was about
is what the mark's span says.

The marks are found before the digests are taken: a path nothing was ever
marked on has no assertion that could have stopped holding, and hashing
its content to discover that is work a buffer with no marks in it should
not pay on every render."
  (let ((mine (seq-filter (lambda (mark) (equal (revu-mark-path mark) path))
                          (revu-review-marks review))))
    (when mine
      (let ((digests (revu-reviewed--digests files path)))
        (seq-remove (lambda (mark)
                      (member (revu-mark-digest mark) digests))
                    mine)))))

(defun revu-reviewed--dangling (review files path)
  "Return every mark of REVIEW on PATH that matches nothing FILES renders.
Answered from `revu-reviewed--dangling-memo' while a render is holding
one, and computed afresh otherwise."
  (if (null revu-reviewed--dangling-memo)
      (revu-reviewed--dangling-marks review files path)
    (let ((memo (gethash path revu-reviewed--dangling-memo 'unasked)))
      (if (eq memo 'unasked)
          (puthash path (revu-reviewed--dangling-marks review files path)
                   revu-reviewed--dangling-memo)
        memo))))

(defun revu-reviewed--stale-p (review files value)
  "Return non-nil when the section of FILES valued VALUE was read and changed.
A region is stale when a mark of REVIEW was taken over it and no longer
matches it.
For a plain file the path is the locality, so any unmatched mark on it is
about the file.  For a hunk it takes the mark's span: the hunk is stale
while some unmatched mark on its path was taken over base lines this hunk
still covers, which is what tells a hunk the reviewer read and an agent
then changed from a hunk they never read at all.  A mark carrying no span
attributes to nothing -- it is better to call read work new than to call
new work read."
  (let* ((path (revu-reviewed--path value))
         (dangling (revu-reviewed--dangling review files path)))
    (when dangling
      (let ((file (revu-reviewed--file files path)))
        (if (and file (revu-diff-file-plain file))
            t
          (and (seq-find
                (lambda (assertion)
                  (and (not (revu-reviewed--marked-p review (car assertion)))
                       (seq-find (lambda (mark)
                                   (revu-reviewed--spans-overlap-p
                                    (revu-mark-span mark) (cdr assertion)))
                                 dangling)))
                (revu-reviewed--assertions files value))
               t))))))

(defun revu-reviewed-state (review files value)
  "Return the Reviewed state of the section of FILES valued VALUE, in REVIEW.
The Reviewed state is `reviewed' when every region under VALUE matches a
mark, `stale' when one of them was read and has changed since, and nil
when none was ever read.  It is derived here on every render and never
persisted, like Anchor state and Path resolution before it."
  (cond ((revu-reviewed-p review files value) 'reviewed)
        ((revu-reviewed--stale-p review files value) 'stale)))

(defun revu-reviewed-progress (review files value)
  "Return how much of the file of FILES valued VALUE has been read, in REVIEW.
It is (READ . ALL), the hunks matching a mark out of the hunks there are.
Return nil unless VALUE is a file with more than one hunk to divide it: a
plain file is read or it is not, and a one-hunk file says the same thing
its glyph already says.  Working down a large file is the case this
answers -- three of five hunks read is neither reviewed nor untouched."
  (unless (consp value)
    (let ((file (revu-reviewed--file files value)))
      (unless (and file (revu-diff-file-plain file))
        (let ((digests (revu-reviewed--digests files value)))
          (when (> (length digests) 1)
            (cons (seq-count (lambda (digest)
                               (revu-reviewed--marked-p review digest))
                             digests)
                  (length digests))))))))

(defun revu-reviewed-totals (review files)
  "Return how much of FILES REVIEW records as read, over the whole Source.
It is (READ TOTAL STALE): the hunks matching a mark, the hunks there are,
and the hunks that were read and have changed since.  Every hunk of every
file takes part, whatever the buffer\='s view filters are leaving out --
a filter is a lens on the Source and not a change of Source, so hiding
what has been read cannot make the figure move.

The dangling marks are memoised across the walk for the same reason a
render memoises them: every hunk of a file asks the same question of the
same marks.  A Review that has never been marked is answered by counting
alone: there is nothing a digest could match, and hashing every line of
the Source to find that out is work every render of an unmarked Review
would pay for a figure already known."
  (let ((hunks (apply #'+ (mapcar (lambda (file)
                                    (length (revu-diff-file-hunks file)))
                                  files))))
    (if (zerop (length (revu-review-marks review)))
        (list 0 hunks 0)
      (let ((revu-reviewed--dangling-memo (make-hash-table :test #'equal))
            (read 0)
            (stale 0))
        (dolist (file files)
          (let ((path (revu-diff-file-path file)))
            (dolist (value (revu-reviewed--hunk-values files path))
              (cond ((revu-reviewed-p review files value) (setq read (1+ read)))
                    ((revu-reviewed--stale-p review files value)
                     (setq stale (1+ stale)))))))
        (list read hunks stale)))))

;;;; The render predicates

(defun revu-reviewed-hidden-p (review files)
  "Return the predicate saying which sections of FILES render collapsed.
A reviewed section comes back collapsed, which is what gets read work out
of the reviewer's way; REVIEW holds the marks that decide it."
  (lambda (value) (revu-reviewed-p review files value)))

(defun revu-reviewed-state-p (review files)
  "Return the function saying how a section of FILES renders its Reviewed state.
It is called with a section's value and returns (STATE . PROGRESS), which
is all the render needs to know about marks: the render draws headings
and REVIEW is what decides them."
  (let ((memo (make-hash-table :test #'equal)))
    (lambda (value)
      (let ((revu-reviewed--dangling-memo memo))
        (cons (revu-reviewed-state review files value)
              (revu-reviewed-progress review files value))))))

(defun revu-reviewed-keep-p (review files)
  "Return the predicate saying which sections of FILES render at all.
It is the current buffer's two filters composed: annotated-only keeps
what carries Annotations, hide-reviewed drops what REVIEW's marks cover,
and with both on a section has to pass both.  Return nil when neither
filter is on, which is the whole Source."
  (let ((hide revu-reviewed-hide-reviewed)
        (annotated-only revu-reviewed-annotated-only))
    (when (or hide annotated-only)
      (lambda (value annotated)
        (and (or (not annotated-only) annotated)
             (not (and hide (revu-reviewed-p review files value))))))))

;;;; Marking

(defun revu-reviewed--section-at-point ()
  "Return the hunk or file section point is in.
Signal a `user-error' when point is in neither: a mark is taken over a
region the reviewer can see, and nothing else is one."
  (let ((section (magit-current-section)))
    (while (and section
                (not (or (object-of-class-p section 'revu-hunk-section)
                         (object-of-class-p section 'revu-file-section))))
      (setq section (oref section parent)))
    (or section (user-error "Point is not in a hunk or a file"))))

(defun revu-reviewed--mark (review path assertions)
  "Return REVIEW with a mark on PATH for each of ASSERTIONS it lacks.
Each mark records the base lines its region covered as well as its
digest, so a mark that stops matching can still be attributed to the hunk
that grew out of those lines."
  (dolist (assertion assertions review)
    (unless (revu-reviewed--marked-p review (car assertion))
      (setq review (revu-review-add-mark
                    review
                    (revu-mark-create path (car assertion) (cdr assertion)))))))

(defun revu-reviewed--unmark (review digests)
  "Return REVIEW without any Reviewed mark asserting one of DIGESTS."
  (dolist (digest digests review)
    (setq review (revu-review-remove-marks review digest))))

(defun revu-reviewed--hunk-values (files path)
  "Return the value of every hunk of FILES under PATH, in Source order.
A hunk's value is its identity across a render, so a walk over these
finds what the buffer holds however the view filters have shaped it."
  (mapcar (lambda (hunk) (revu-render-hunk-value path hunk))
          (revu-reviewed--hunks files path)))

(defun revu-reviewed--section-values (files)
  "Return the value of every file and hunk of FILES, in Source order."
  (seq-mapcat (lambda (file)
                (let ((path (revu-diff-file-path file)))
                  (cons path (revu-reviewed--hunk-values files path))))
              files))

(defun revu-reviewed--siblings-after (files value)
  "Return the siblings of VALUE in FILES that follow it, nearest first.
A hunk's siblings are the rest of the hunks of its file, and then, off
the end of them, the files below its own: marking the last hunk of a file
finishes that file, and what comes next is the next file.  A file's
siblings are the files below it, its own hunks being under it rather than
beside it."
  (let* ((path (revu-reviewed--path value))
         (later (cdr (member path (mapcar #'revu-diff-file-path files)))))
    (if (consp value)
        (append (cdr (member value (revu-reviewed--hunk-values files path)))
                later)
      later)))

(defun revu-reviewed--sections-after (files value)
  "Return the values of FILES that come after VALUE in Source order.
The hunks of a file are under it rather than after it, so a file's own
hunks are none of them: they are the section the reviewer just marked,
seen from the inside."
  (let ((rest (cdr (member value (revu-reviewed--section-values files)))))
    (if (consp value)
        rest
      (seq-drop-while (lambda (other)
                        (equal (revu-reviewed--path other) value))
                      rest))))

(defun revu-reviewed--nearest-position (files value)
  "Return where point can be left nearest the section of FILES valued VALUE.
Its own heading when that is on screen, and otherwise the heading of the
nearest section rendered after it in Source order, or of the nearest one
before it.  This is where a mark with nothing after it to advance to
leaves the reviewer: with `revu-reviewed-hide-reviewed' on, marking the
last section takes it out of the buffer, and the section above it is as
close to where they were as the render can put them."
  (or (revu-render-heading-position value)
      (seq-some #'revu-render-heading-position
                (revu-reviewed--sections-after files value))
      (seq-some #'revu-render-heading-position
                (nreverse (seq-take-while
                           (lambda (other) (not (equal other value)))
                           (revu-reviewed--section-values files))))))

(defun revu-reviewed--advance (files after)
  "Put point on the heading of the first sibling rendered after AFTER.
AFTER is the value of the section of FILES that was just marked, and the
sibling is taken reviewed or not: the advance says where the reviewer is
in the Source, and stepping over what they have marked already would land
them somewhere they cannot predict from what is on screen.

The walk is over the Source's order rather than the buffer's, because
with `revu-reviewed-hide-reviewed' on what was just marked has left the
buffer and there is no section there to walk on from.  A heading under a
fold is stood for by the heading of the fold, so no gesture of marking
ever puts point in text the reviewer cannot see or opens a fold of theirs
to make room (`revu-render-heading-position').

With no sibling after it left in the buffer the reviewer has read to the
end of what is shown, and point stays as near to what they marked as the
render allows: on its own heading, or, once a view filter has taken that
away, on the nearest heading after it or before it."
  (let ((position (or (seq-some #'revu-render-heading-position
                                (revu-reviewed--siblings-after files after))
                      (revu-reviewed--nearest-position files after))))
    (when position
      (goto-char position))))

(defun revu-reviewed--forget-visibility (section)
  "Forget every fold a Reviewed mark on SECTION has just taken over.
SECTION is one of the sections that was marked, so its own visibility and
that of everything it covers is the marks' to decide again.  So is the
file's: marking the last unread hunk of a file makes the file read.
Nothing else is forgotten -- a sibling hunk the reviewer folded by hand,
and has not read, keeps its fold across the render."
  (revu-render-forget-visibility-tree section)
  (let ((file (oref section parent)))
    (while (and file (not (object-of-class-p file 'revu-file-section)))
      (setq file (oref file parent)))
    (when file
      (revu-render-forget-visibility file))))

(defun revu-reviewed--selection ()
  "Return the run of sibling sections under the region, or nil for none.
The region means two things in a review buffer and this is the one that
marks: beginning and ending in sibling headings, it selects the sections
between them.  Inside one section's body it is a run of Source lines
instead, which is what an Annotation is taken over.  `magit-region-sections'
draws the line -- it answers nil unless both ends sit in a heading, which
a body-internal region never does (ADR-0008)."
  (magit-region-sections))

(defun revu-reviewed--mark-sections (review files values unmark)
  "Return REVIEW with the sections of FILES valued VALUES marked, or unmarked.
UNMARK non-nil drops the marks over the content that is there now instead
of taking them.  Every section is folded into the one Review returned
rather than written as it is reached: a run of hunks is one Sidecar write
and one render, and the render is what a large Source is expensive to
redraw.

Return (REVIEW . MARKED), where MARKED is the values something was
asserted over.  A section with nothing to assert -- a rename that changed
no line -- is passed over and is not in it."
  (let ((marked nil))
    (dolist (value values (cons review (nreverse marked)))
      (let ((assertions (revu-reviewed--assertions files value)))
        (when assertions
          (push value marked)
          (setq review
                (if unmark
                    (revu-reviewed--unmark review (mapcar #'car assertions))
                  (revu-reviewed--mark review (revu-reviewed--path value)
                                       assertions))))))))

(defun revu-reviewed--place-point (files marked unmark)
  "Put point where a gesture over the sections valued MARKED should leave it.
Marking moves the reviewer on from the last section of FILES it marked,
so a run advances from its end rather than from its beginning.
UNMARK moves point nowhere at all: taking a mark back is not reading
anything, and the reviewer is left looking at what they just changed
their mind about."
  (unless unmark
    (revu-reviewed--advance files (car (last marked)))))

;;;###autoload
(defun revu-reviewed-toggle (&optional unmark)
  "Mark the hunk or file point is in reviewed, or unmark it.
A hunk is marked on its own; a file is marked one hunk at a time, because
a diff persists hunk marks only (ADR-0009).  Marking collapses what it
marks and moves point on to the heading of the next sibling rendered
after it, reviewed or not -- the next hunk of the file, or the next file
once the last hunk of one is marked -- and onto the heading of the fold
instead whenever that sibling lies under one.  Unmarking moves point nowhere; it
drops only the marks over the content that is there now, so an assertion
about content that has since changed is left where it is.

With the region selecting a run of sibling headings, every hunk or file
in the run is marked in one gesture, in one Sidecar write and one render.
A selection always marks and never flips, so a section in it that was
already read keeps its mark.  Sections in it with nothing to mark are
passed over and the skip is reported.

With a prefix argument, UNMARK, the selection is unmarked instead -- or
the section at point, when there is no selection."
  (interactive "P")
  (let* ((selection (revu-reviewed--selection))
         (sections (or selection (list (revu-reviewed--section-at-point))))
         (values (mapcar (lambda (section) (oref section value)) sections))
         (files revu--files)
         (review (revu-review))
         ;; Only a lone section flips: over a selection the reviewer is
         ;; saying "I have read all of this", which is not an answer that
         ;; depends on what each section was before (ADR-0009).
         (unmark (if unmark
                     t
                   (and (not selection)
                        (revu-reviewed-p review files (car values))))))
    (pcase-let ((`(,written . ,marked)
                 (revu-reviewed--mark-sections review files values unmark)))
      (unless marked
        (if selection
            (user-error "Nothing in the selection can be marked reviewed")
          (user-error "There is nothing here to mark reviewed")))
      (revu-sidecar-write revu--sidecar written)
      ;; What the reviewer folded by hand outranks the HIDE a render
      ;; derives from the marks, and rightly so -- but where the marks
      ;; have just changed, they have the last word.  Forgetting the folds
      ;; there leaves the render free to collapse what was marked, and open
      ;; what was unmarked, from the state alone (ADR-0008).
      (dolist (section sections)
        (when (member (oref section value) marked)
          (revu-reviewed--forget-visibility section)))
      (revu-render)
      (revu-reviewed--place-point files marked unmark)
      (let ((skipped (- (length values) (length marked))))
        (when (> skipped 0)
          (message "Skipped %d section%s with nothing to mark"
                   skipped (if (= skipped 1) "" "s")))))))

;;;; The filters

;;;###autoload
(defun revu-reviewed-toggle-hide-reviewed ()
  "Leave the sections marked Reviewed out of the buffer, or put them back."
  (interactive)
  (setq revu-reviewed-hide-reviewed (not revu-reviewed-hide-reviewed))
  (revu-render)
  (message "Reviewed sections are %s"
           (if revu-reviewed-hide-reviewed "hidden" "shown")))

;;;###autoload
(defun revu-reviewed-toggle-annotated-only ()
  "Render only what carries Annotations, or the whole Source again."
  (interactive)
  (setq revu-reviewed-annotated-only (not revu-reviewed-annotated-only))
  (revu-render)
  (message "Rendering %s"
           (if revu-reviewed-annotated-only
               "only what is annotated"
             "the whole Source")))

(provide 'revu-reviewed)
;;; revu-reviewed.el ends here
