;;; revu-reviewed.el --- Mark what has been read as Reviewed  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Jonas Rodrigues

;; Author: Jonas Rodrigues

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; A Reviewed mark is the reviewer's assertion that they have read a
;; region, and the digest of what they read is the mark's identity
;; (ADR-0009).  Whether the assertion still holds is derived, never
;; stored: a hunk is reviewed exactly while its current content hashes to
;; some mark, so an edit un-reviews it with no staleness flag to keep in
;; step, and reverting the edit brings the mark back.  Marks that match
;; nothing are kept for exactly that reason.
;;
;; A diff persists hunk marks only.  Marking a file reviewed takes one
;; mark per hunk, and the file reads as reviewed while every hunk of it
;; matches -- a file-level mark could go on claiming the file was read
;; after a hunk under it changed, which is the lie this design exists to
;; prevent.
;;
;; The digest covers the hunk's body lines with the origin character each
;; diff line carries, and nothing else: the `@@' header and the line
;; numbers around it regenerate on every `git diff' and are no part of
;; what the reviewer read.
;;
;; Marking collapses what it marks and moves the reviewer on to the next
;; hunk they have not read.  Two buffer-local filters -- annotated-only
;; and hide-reviewed -- shape the render and compose: reviewed and
;; annotated are orthogonal, so a hunk with an open question can be
;; marked reviewed and still be found by the annotated-only filter.
;;
;; Reviewed marks are reviewer-private: the Export drops them and the
;; agent contract says nothing about them.

;;; Code:

(require 'cl-lib)
(require 'magit-section)
(require 'seq)
(require 'revu-diff)
(require 'revu-record)
(require 'revu-render)
(require 'revu-sidecar)

;; The review buffer's state and its render live in `revu.el', which
;; requires this file; naming them here would be a loading cycle.
(defvar revu--sidecar)
(defvar revu--files)
(declare-function revu-render "revu")
(declare-function revu-review "revu")

(defvar-local revu-reviewed-hide-reviewed nil
  "Non-nil while this review buffer leaves reviewed sections out.")

(defvar-local revu-reviewed-annotated-only nil
  "Non-nil while this review buffer renders only what carries Annotations.")

;;;; What a mark is taken over

(defun revu-reviewed-hunk-digest (hunk)
  "Return the digest identifying the content of HUNK.
Only the hunk's body lines take part, each with the origin character the
diff wrote it with.  The `@@' header is left out: its boundaries and
numbers are regenerated by every diff and say nothing about whether the
reviewer has read these lines (ADR-0009)."
  (revu-digest (mapconcat (lambda (line) (nth 2 line))
                          (revu-diff-hunk-lines hunk)
                          "\n")))

(defun revu-reviewed--file (files path)
  "Return the file of FILES rendered at PATH, or nil when there is none."
  (seq-find (lambda (file) (equal (revu-diff-file-path file) path)) files))

(defun revu-reviewed--hunks (files value)
  "Return the hunks of FILES the section valued VALUE covers, in render order.
VALUE is a file section's value -- the path -- or a hunk section's, which
is the path and the `@@' header the hunk was rendered with."
  (if (consp value)
      (let ((file (revu-reviewed--file files (car value))))
        (seq-filter (lambda (hunk) (equal (revu-diff-hunk-header hunk) (cdr value)))
                    (and file (revu-diff-file-hunks file))))
    (let ((file (revu-reviewed--file files value)))
      (and file (revu-diff-file-hunks file)))))

(defun revu-reviewed--digests (files value)
  "Return the digest of each hunk of FILES the section valued VALUE covers."
  (mapcar #'revu-reviewed-hunk-digest (revu-reviewed--hunks files value)))

(defun revu-reviewed--path (value)
  "Return the path the section valued VALUE belongs to."
  (if (consp value) (car value) value))

;;;; Whether a mark still holds

(defun revu-reviewed--marked-p (review digest)
  "Return non-nil when some mark of REVIEW asserts DIGEST was read."
  (seq-find (lambda (mark) (equal (revu-mark-digest mark) digest))
            (revu-review-marks review)))

(defun revu-reviewed-p (review files value)
  "Return non-nil when REVIEW records the section of FILES valued VALUE as read.
A hunk is reviewed while its content matches a mark; a file while every
hunk of it does.  A file showing no hunks at all -- a rename that changed
nothing -- is not reviewed by vacuity: there is nothing a mark could have
been taken over."
  (let ((digests (revu-reviewed--digests files value)))
    (and digests
         (not (seq-find (lambda (digest)
                          (not (revu-reviewed--marked-p review digest)))
                        digests)))))

;;;; The render predicates

(defun revu-reviewed-hidden-p (review files)
  "Return the predicate saying which sections of FILES render collapsed.
A reviewed section comes back collapsed, which is what gets read work out
of the reviewer's way; REVIEW holds the marks that decide it."
  (lambda (value) (revu-reviewed-p review files value)))

(defun revu-reviewed-keep-p (review files)
  "Return the predicate saying which sections of FILES render at all.
It is the current buffer's two filters composed: annotated-only keeps
what carries Annotations, hide-reviewed drops what REVIEW's marks cover,
and with both on a section has to pass both.  Return nil when neither
filter is on, which is the whole Source."
  (let ((hide revu-reviewed-hide-reviewed)
        (annotated-only revu-reviewed-annotated-only))
    (when (or hide annotated-only)
      (lambda (value annotated)
        (and (or (not annotated-only) annotated)
             (not (and hide (revu-reviewed-p review files value))))))))

;;;; Marking

(defun revu-reviewed--section-at-point ()
  "Return the hunk or file section point is in.
Signal a `user-error' when point is in neither: a mark is taken over a
region the reviewer can see, and nothing else is one."
  (let ((section (magit-current-section)))
    (while (and section
                (not (or (object-of-class-p section 'revu-hunk-section)
                         (object-of-class-p section 'revu-file-section))))
      (setq section (oref section parent)))
    (or section (user-error "Point is not in a hunk or a file"))))

(defun revu-reviewed--mark (review path digests)
  "Return REVIEW with a mark on PATH for each of DIGESTS it lacks."
  (dolist (digest digests review)
    (unless (revu-reviewed--marked-p review digest)
      (setq review (revu-review-add-mark review (revu-mark-create path digest))))))

(defun revu-reviewed--unmark (review digests)
  "Return REVIEW without any Reviewed mark asserting one of DIGESTS."
  (dolist (digest digests review)
    (setq review (revu-review-remove-marks review digest))))

(defun revu-reviewed--advance (from)
  "Put point on the first unreviewed hunk section rendered after FROM.
Point stays where it is when there is none: the reviewer has read to the
end of what is rendered, and moving them anywhere else would be a guess."
  (let ((review (revu-review))
        (files revu--files)
        (best nil))
    (cl-labels ((walk (section)
                  (when (and (null best)
                             (object-of-class-p section 'revu-hunk-section)
                             (>= (oref section start) from)
                             (not (revu-reviewed-p review files
                                                   (oref section value))))
                    (setq best section))
                  (unless best (mapc #'walk (oref section children)))))
      (walk magit-root-section))
    (when best
      (goto-char (oref best start)))))

;;;###autoload
(defun revu-reviewed-toggle ()
  "Mark the hunk or file point is in reviewed, or unmark it.
A hunk is marked on its own; a file is marked one hunk at a time, because
a diff persists hunk marks only (ADR-0009).  Marking collapses what it
marks and moves point on to the next hunk not read yet; unmarking drops
only the marks over the content that is there now, so an assertion about
content that has since changed is left where it is."
  (interactive)
  (let* ((section (revu-reviewed--section-at-point))
         (value (oref section value))
         (files revu--files)
         (digests (revu-reviewed--digests files value))
         (review (revu-review)))
    (unless digests
      (user-error "There is nothing here to mark reviewed"))
    (let ((marking (not (revu-reviewed-p review files value))))
      (revu-sidecar-write revu--sidecar
                          (if marking
                              (revu-reviewed--mark review
                                                   (revu-reviewed--path value)
                                                   digests)
                            (revu-reviewed--unmark review digests)))
      (revu-render)
      ;; A section that was already on screen keeps the visibility it had
      ;; through a re-render, so the mark's collapse is asked for outright
      ;; rather than left to the HIDE a first render would have used.
      (let ((rendered (revu-render-section-with-value value)))
        (cond
         (rendered
          (if marking
              (magit-section-hide rendered)
            (magit-section-show rendered))
          (goto-char (oref rendered start))
          (when marking
            (revu-reviewed--advance (oref rendered end))))
         ;; With hide-reviewed on, what was just marked is not in the
         ;; buffer at all.  There is nothing to collapse, but the reviewer
         ;; still asked to be moved on, so advance from where the render
         ;; left them.
         (marking
          (revu-reviewed--advance (point))))))))

;;;; The filters

;;;###autoload
(defun revu-reviewed-toggle-hide-reviewed ()
  "Leave the sections marked Reviewed out of the buffer, or put them back."
  (interactive)
  (setq revu-reviewed-hide-reviewed (not revu-reviewed-hide-reviewed))
  (revu-render)
  (message "Reviewed sections are %s"
           (if revu-reviewed-hide-reviewed "hidden" "shown")))

;;;###autoload
(defun revu-reviewed-toggle-annotated-only ()
  "Render only what carries Annotations, or the whole Source again."
  (interactive)
  (setq revu-reviewed-annotated-only (not revu-reviewed-annotated-only))
  (revu-render)
  (message "Rendering %s"
           (if revu-reviewed-annotated-only
               "only what is annotated"
             "the whole Source")))

(provide 'revu-reviewed)
;;; revu-reviewed.el ends here
